name: Deploy to EC2  
# masterにpushされた時にjobを実行する
on:
  push:
    branches: [ develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }} 
    steps:
      - id: step1
        run: echo "$SECRET_KEY" > secret_key
      - id: step2
        run: chmod 600 secret_key
      - id: step3
        run: ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "cd ~/pinterest_prince_go_2 && git pull origin master"
